# Generated by Django 5.0.8 on 2024-08-21 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='email_adddress',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
